### ISSUE TITLE
Suggestion: move to the php-fig

### ISSUE THREAD

**Issue by lisachenko** [container-interop/container-interop#16]
It's a good idea to create general interfaces for DI, however I would like to see them in php-fig and accepted as PSR-x. Because it's only the right way to make it usable by developers.
I had a try with https://github.com/aopalliance/php to do the same: define general interfaces, but without success. Nobody wants to include interfaces to their code. So I recommend you to fight for PSR :)

**Comment by Isinlor** [comment]
Hi, I'm new here - just want to ask - is someone working on moving container interop to FIG or planning to do so in foreseeable future? Thanks!

**Comment by mnapoli** [comment]
@Isinlor coming in the next days ;)

**Comment by moufmouf** [comment]
This is well on the way. We juste opened a thread on the PHP-FIG mailing list: https://groups.google.com/forum/#!topic/php-fig/o_jFaRoLfAo

We need support from all of you who might be interested in seeing *container-interop* become a PSR so do not hesitate to voice your opinion in the thread!

**Comment by Potherca** [comment]
As [voting is underway](https://groups.google.com/forum/#!searchin/php-fig/psr-11%7Csort:relevance/php-fig/bU_iHdk38nE/XJoYk7Q7BAAJ), this issue can be closed, right?

**Comment by moufmouf** [comment]
Mmmm... right :)
