### ISSUE TITLE
Delegate lookup feature: request for comments

### ISSUE THREAD

**Issue by moufmouf** [container-interop/container-interop#23]
Hi,

This issue is a follow-up to the 2 merge requests regarding the delegate lookup feature (#20 and #8).

I merged all PRs into a special branch that will be easier to work on:

https://github.com/container-interop/container-interop/tree/delegate-lookup

I split the delegate lookup document into a [main document](https://github.com/container-interop/container-interop/blob/delegate-lookup/docs/delegate_lookup.md) and a [meta document](https://github.com/container-interop/container-interop/blob/delegate-lookup/docs/delegate_lookup-meta.md).

We definitely need some feedback on both.

I hope the meta document will help people joining the discussion to understand what was the process so far (especially useful when we open the discussion on the FIG mailing list again). If you could look at it and let me know if you think it represents what was said so far, it would be great.

**Comment by XedinUnknown** [comment]
Hi all!

Sorry if this is a wrong place to post. Please direct me to an appropriate thread, if so.

I, like many other people, strongly feel that there definitely should be an interface to formalize the delegate lookup feature. Of course, forcing the implementation to have a setter would be wrong. But why not have a getter instead?  
Specifically to demonstrate how this could work, I have created a quick implementation of a DI container, together with my take on the delegate lookup feature: please find it [here](https://github.com/XedinUnknown/di).

I would really like to see the delegate lookup standard backed by an interface. Please let me know what you think about my idea.

**Comment by moufmouf** [comment]
Hey @XedinUnknown,

I must admit I won't have too much time to look at this until the beginning of next week but it looks interesting, especially the fact that you can have "Unlimited level of nesting". At least, we never spoke about such an idea.

What you could do however is start a new issue with your idea, or simply post it on the [PHP-FIG mailing list](https://groups.google.com/forum/#!forum/php-fig) (since we are in the process of adopting PSR-11 and all changes will likely be ported by PSR-11 rather than by container-interop now). So far discussions about PSR-11 have never been too much about the delegate lookup feature and maybe we might need some exposal for this.

**Comment by XedinUnknown** [comment]
@moufmouf, thanks for the quick response.

For some reason I always have trouble reading the mailing list, particularly understanding what is where. Due to this, I would much prefer a GitHub issue: it's so much easier to read and understand.  
Nevertheless, I am happy to create the new thread, if this is a better way to go; please find it [here](https://groups.google.com/forum/#!topic/php-fig/7OOawymvmlQ).

Looking forward to your feedback.
