### ISSUE TITLE
Facade implementation

### ISSUE THREAD

**Issue by mbunge** [container-interop/container-interop#46]
Hello,

I just developed a smart Facade which is using container-interop ContainerInterface. My intention is to use this facade implementation to minimize complexity and provide exchangeable services which are defined by contract.

Facades is supporting all container implementations. Facades suggest thephpleague/container for unittesting.

https://github.com/phpthinktank/blast-facades

I would be happy, if you think this package is usefull, to get mentioned as supporting project.

Best Regards

**Comment by Ocramius** [comment]
You should add it to "projects that use the containerinterface" :-)

**Comment by mbunge** [comment]
Done ;)
