### ISSUE TITLE
Compatible project: Zit

### ISSUE THREAD

**Issue by inxilpro** [container-interop/container-interop#67]
The latest release of my DI container, [Zit](https://github.com/inxilpro/Zit), is container-interop compatible. What is the process of having it added to the list?

**Comment by mnapoli** [comment]
Hi @inxilpro, send a pull request to add it to the list: https://github.com/container-interop/container-interop#projects-implementing-containerinterface The list is ordered alphabetically.

**Comment by mnapoli** [comment]
Closed by #68
