### ISSUE TITLE
Data Manager implements container-interop

### ISSUE THREAD

**Issue by chrismichaels84** [container-interop/container-interop#85]
I have created a data-manager at https://github.com/chrismichaels84/data-manager that is fully implements container-interop.

At its core, data-manager is a simple container with some sugar. What makes it different is that everything is done using traits. There are several extra traits (di container, loading config files, collections, etc) that can be mixed and matched to integrate data-manager directly into an existing project.

Everything is well unit tested, documented, and follows psr conventions and SOLID principles.

I would love to chat about inclusion on this list.

Thank you.

**Comment by moufmouf** [comment]
Hey Michael!

Nice work! I've had a quick look at the documentation and it can really prove useful for managing configuration of projects.

Do not hesitate to open a PR adding your project on the README.md of container-interop and I'll accept it.

**Comment by chrismichaels84** [comment]
I've opened the PR and am closing this issue. Thanks!
