### ISSUE TITLE
Default value for get

### ISSUE THREAD

**Issue by cookiekiller** [container-interop/container-interop#87]
I'd like to suggest a change of the get api.

Current:
```PHP
    $container->get($id); // throws exception if $id not found
```

Suggestion
```PHP
    $container->get($id, null); // returns null if $id not found
    $container->get($id, false); // returns false if $id not found
    $container->get($id); // throws exception if $id not found
```

I'm not sure if it fits the idea of the container-interop. Anyway I'd like to requests comments and talk about it.

Regards

**Comment by drealecs** [comment]
Hi Michael,

One can implement it in his own client code but I don't recommend it as
it's smelly.

Alex

**Comment by mnapoli** [comment]
Hi @cookiekiller, this would be a big incompatibility with most containers.

**Comment by moufmouf** [comment]
For information, the signature of `get` was inspired by analyzing most of the containers out there.

Adding a second parameter for a default value is certainly a nice feature for users but it does not do more.

I see 2 reasons not to do it:

1- the `ContainerInterface` is not meant to be used by end users (that would mean using a container as a service locator) but by frameworks. Being "nice" to users is a way to telling them it is ok to use `get` in their code. It is not. Frameworks can deal with the fact that a NotFoundException is always thrown.
2- you can easily write a wrapper class around `ContainerInterface` to implement this feature if you deem it useful.

**Comment by cookiekiller** [comment]
@moufmouf thank you for these insides, that was the missing piece of information I was looking for.

**Comment by moufmouf** [comment]
You're welcome!
